version: "3.3"

services: 
    stratepig_server:
        build: .
        ports:
            - 32500:32500
        stdin_open: true
    stratepig_updater:
        build: ./stratepig_updater
        ports:
            - 4001:4001
        volumes:
            - updater:/files
volumes:
    updater: