[package]
name = "stratepig_core"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>"]
edition = "2018"

[dependencies]
vec_map = "0.8.2"
log = "0.4.14"
byteorder = "1.4.3"
parking_lot = "0.11.1"