[package]
name = "stratepig_core"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>"]
edition = "2018"

[dependencies]
vec_map = "0.8.2"
mio = "0.7.13"
byteorder = "1.4.3"